### ISSUE TITLE
Syntax error in example

### ISSUE THREAD

**Issue by jcubic** [Fedia/unclejs#1]
I think that this will throw error:
```javascript
var TodoItem = uncle.render('<li class="todo-{{complete? 'complete' : 'active'}}" onclick="this.toggle($index)">{{text}}<li>');
```
it will not be interpolation template that have `'complete'` but it close main string (you can see on github complete is in different color). to fix this you need to escape quote or use template literals.
```javascript
var TodoItem = uncle.render(`<li class="todo-{{complete? 'complete' : 'active'}}" onclick="this.toggle($index)">{{text}}<li>`);
```

**Comment by Fedia** [comment]
Oopsie, thanks @jcubic
